### ISSUE TITLE
panic: not subscribed to board

### ISSUE THREAD

**Issue by vyloy** [skycoin/bbs#12]
not subscribed to board

2017/06/13 17:53:04 not subscribed to board
panic: not subscribed to board

goroutine 42 [running]:
log.Panic(0xc4204ddcb0, 0x1, 0x1)
	/usr/local/go/src/log/log.go:322 +0xc0
github.com/skycoin/bbs/extern/dev.(*Tester).getRandomPostRef(0xc42036e000, 0x2745dab29747316, 0x812187796a5a352e, 0x1b79e8b04d64766c, 0xd986a1beeec6b6b, 0x0, 0x0, 0x0, 0x0, 0x37)

**Comment by evanlinjin** [comment]
Did you unsubscribe to the board while running test mode?

**Comment by evanlinjin** [comment]
Unsubscribe is mean't to delete board if we own it. Might need a warning to tell user.

**Comment by vyloy** [comment]
It looks like it will panic after call api/unsubscribe more than one time.
I think is better not to panic

**Comment by evanlinjin** [comment]
Okay I'll fix it!
