### ISSUE TITLE
Have `run.sh` script

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/bbs#120]
Put .sh script, like skycoin repo has, run.sh to start node for bbs

**Comment by gz-c** [comment]
a simple makefile would be better

**Comment by evanlinjin** [comment]
@gz-c Can I have an example please?

**Comment by gz-c** [comment]
@evanlinjin https://github.com/gz-c/skycoin/blob/10d9efd1c2f9486d18c9affa043dab239731be2d/Makefile

**Comment by gz-c** [comment]
run.sh has the advantage in that its more convenient to pass args to it with `$@`... 
To do this with make, you need to invoke make like
`make ARGS="--foo=bar --bat=baz" run`

**Comment by evanlinjin** [comment]
#125
