### ISSUE TITLE
Sometimes error message does not close on click.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/bbs#142]
Maarten on Telegram:
> Only feedback I have right now, is that I could not click away error message (when failed attempt to register username). F5 solved the problem.

![image](https://user-images.githubusercontent.com/14065705/31059996-9b2155f0-a767-11e7-9cde-c1b2c99197d4.png)

@feifeiwoye :
> please dont return different result for the same thing, you can return null or [], but not [null] or other things...

**Comment by feifeiwoye** [comment]
please dont return different result for the same thing, you can return null or [], but not [null] or other things...

**Comment by feifeiwoye** [comment]
I fixed the problem last week

**Comment by evanlinjin** [comment]
Got it!
