### ISSUE TITLE
UI Needs Some Changes.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/bbs#18]
1. All Boards Page needs `Subscribe` button. This makes use of the new subscribe endpoint (check postman collection). A dialog should pop up asking for address and board public key.

2. When listing threads of a board, the header should show details of the board itself (Maybe the `get_boardpage` endpoint will be helpful here).

3. When listing threads of a board, only two columns are needed; "Thread" and "Description". Everything else is to be hidden away in a "more info" button.

4. When listing threads of a board, we need some indication whether the thread is imported from another board or not. My solution to this is to have "(Imported)" written next to the Thread name. But you can be creative on how to do this.

5. Only master nodes can create new boards and import threads. Only show these options if the node is master.

Otherwise, this is one awesome user interface. Love the post adding dialog :)

**Comment by evanlinjin** [comment]
Awesome work so far!

However you missed out number 5.
> 5. Only master nodes can create new boards and import threads. Only show these options if the node is master.

**Comment by vyloy** [comment]
#31 Fixed
