### ISSUE TITLE
Non unique ids in html

### ISSUE THREAD

**Issue by cyberbolt** [skycoin/bbs#212]
Identity creation form password and confirm password fields have the same ids
![image](https://user-images.githubusercontent.com/771535/34681792-f8be7894-f4ad-11e7-9f43-618c1763b3f5.png)

**Comment by feifeiwoye** [comment]
error? If there are no errors, this has no effect on ng.

**Comment by cyberbolt** [comment]
1. If you put in your password into both fields and decide to click on 'eye' to see it without *, you may notice some weird bechavior of that fields - you can make show up only confirm password field, the original password is never opened,

2. Chrome console has error - the OP img is from console.

**Comment by feifeiwoye** [comment]
@cyberbolt Thanks. I have fixed it.
