### ISSUE TITLE
[Bug] Changing users in user info goes to a 404 page. 

### ISSUE THREAD

**Issue by entity5459** [skycoin/bbs#26]
[Bug] Changing users in user info goes to a 404 page. URL is. http://127.0.0.1:7410/user

**Comment by evanlinjin** [comment]
Can't seem to replicate this bug. Can you please give me some directions? What command line flags did you change, etc.
https://youtu.be/RMhzML0-5jY

**Comment by evanlinjin** [comment]
Invalid.
