### ISSUE TITLE
Build bbs into single executable that can launch CXO and web front-end. 

### ISSUE THREAD

**Issue by entity5459** [skycoin/bbs#28]
Build bbs into single executable that can launch CXO and web front-end. 

When clicking the executable CXO should start in the background and a web browser should open automatically to the BBS page. There should also be an option to close CXO.

**Comment by evanlinjin** [comment]
> When clicking the executable CXO should start in the background and a web browser should open automatically to the BBS page.
Don't we have this already?

> There should also be an option to close CXO.
Please elaborate!

**Comment by evanlinjin** [comment]
I've implemented a quit endpoint: b3af0b48de6413dab5ffeaaa2d9eb1824a3710f4
Is this what was needed?
